export type QuizQuestion = {
  question: string;
  options: [string, string, string, string];
  correct_option_index: number;
  correct_answer: string;
  explanation: string;
  scripture_references: string[];
  category: string;
  difficulty: "easy" | "medium" | "hard";
};

export const fallbackQuizQuestions: QuizQuestion[] = [
  {
    question: "Which woman hid two Israelite spies in Jericho?",
    options: ["Rahab", "Deborah", "Ruth", "Miriam"],
    correct_option_index: 0,
    correct_answer: "Rahab",
    explanation: "Rahab protected the spies before Israel entered the land, and they promised mercy to her household.",
    scripture_references: ["Joshua 2:1-14"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which disciple asked to see the nail marks before believing Jesus had risen?",
    options: ["Andrew", "Thomas", "Philip", "James"],
    correct_option_index: 1,
    correct_answer: "Thomas",
    explanation: "Thomas was absent when Jesus first appeared to the disciples and later confessed faith after seeing Him.",
    scripture_references: ["John 20:24-29"],
    category: "Resurrection",
    difficulty: "easy",
  },
  {
    question: "What did God provide each morning for Israel in the wilderness?",
    options: ["Olives", "Manna", "Grapes", "Honey"],
    correct_option_index: 1,
    correct_answer: "Manna",
    explanation: "The Lord provided manna daily as bread from heaven for Israel during their journey.",
    scripture_references: ["Exodus 16:13-18"],
    category: "Wilderness",
    difficulty: "easy",
  },
  {
    question: "Who interpreted Pharaoh's dreams in Egypt?",
    options: ["Joseph", "Moses", "Daniel", "Samuel"],
    correct_option_index: 0,
    correct_answer: "Joseph",
    explanation: "Joseph told Pharaoh that God had revealed the coming years of plenty and famine.",
    scripture_references: ["Genesis 41:14-32"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "Which judge led Israel after hearing from the prophetess Deborah?",
    options: ["Gideon", "Barak", "Samson", "Ehud"],
    correct_option_index: 1,
    correct_answer: "Barak",
    explanation: "Deborah summoned Barak and gave him the Lord's command concerning Sisera.",
    scripture_references: ["Judges 4:4-10"],
    category: "Judges",
    difficulty: "medium",
  },
  {
    question: "What object did David use to defeat Goliath?",
    options: ["A spear", "A sling and stone", "A sword", "A bow"],
    correct_option_index: 1,
    correct_answer: "A sling and stone",
    explanation: "David struck Goliath with a stone from his sling and the giant fell.",
    scripture_references: ["1 Samuel 17:49"],
    category: "Bible events",
    difficulty: "easy",
  },
  {
    question: "Who was swallowed by a great fish after fleeing from God's command?",
    options: ["Jonah", "Nahum", "Micah", "Hosea"],
    correct_option_index: 0,
    correct_answer: "Jonah",
    explanation: "Jonah ran from the mission to Nineveh, and the Lord appointed a great fish to swallow him.",
    scripture_references: ["Jonah 1:17"],
    category: "Prophets",
    difficulty: "easy",
  },
  {
    question: "Which city did God spare after its people repented at Jonah's preaching?",
    options: ["Babylon", "Nineveh", "Jericho", "Tyre"],
    correct_option_index: 1,
    correct_answer: "Nineveh",
    explanation: "Nineveh believed God, turned from evil, and God showed mercy.",
    scripture_references: ["Jonah 3:5-10"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "Who asked God for wisdom to govern the people?",
    options: ["Saul", "Solomon", "Hezekiah", "Josiah"],
    correct_option_index: 1,
    correct_answer: "Solomon",
    explanation: "Solomon asked for an understanding heart, and God was pleased with his request.",
    scripture_references: ["1 Kings 3:7-12"],
    category: "Kings",
    difficulty: "easy",
  },
  {
    question: "Which prophet saw dry bones come to life in a vision?",
    options: ["Isaiah", "Ezekiel", "Jeremiah", "Amos"],
    correct_option_index: 1,
    correct_answer: "Ezekiel",
    explanation: "Ezekiel saw a valley of dry bones restored as a sign of God's power to revive Israel.",
    scripture_references: ["Ezekiel 37:1-10"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "Who baptized Jesus in the Jordan River?",
    options: ["Peter", "John the Baptist", "James", "Philip"],
    correct_option_index: 1,
    correct_answer: "John the Baptist",
    explanation: "Jesus came to John at the Jordan to be baptized before beginning His public ministry.",
    scripture_references: ["Matthew 3:13-17"],
    category: "Jesus",
    difficulty: "easy",
  },
  {
    question: "What did Jesus turn into wine at Cana?",
    options: ["Oil", "Milk", "Water", "Vinegar"],
    correct_option_index: 2,
    correct_answer: "Water",
    explanation: "At the wedding in Cana, Jesus changed water into wine as His first recorded sign in John.",
    scripture_references: ["John 2:1-11"],
    category: "Jesus",
    difficulty: "easy",
  },
  {
    question: "Which parable tells of a son who wasted his inheritance and returned home?",
    options: ["The Good Samaritan", "The Prodigal Son", "The Sower", "The Talents"],
    correct_option_index: 1,
    correct_answer: "The Prodigal Son",
    explanation: "Jesus told of a lost son welcomed by his father to show mercy and restoration.",
    scripture_references: ["Luke 15:11-24"],
    category: "Parables",
    difficulty: "easy",
  },
  {
    question: "Who climbed a sycamore tree to see Jesus?",
    options: ["Zacchaeus", "Nicodemus", "Bartimaeus", "Jairus"],
    correct_option_index: 0,
    correct_answer: "Zacchaeus",
    explanation: "Zacchaeus climbed the tree because he was short and wanted to see Jesus passing by.",
    scripture_references: ["Luke 19:1-6"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which apostle was formerly known as Saul of Tarsus?",
    options: ["Peter", "Paul", "Barnabas", "Silas"],
    correct_option_index: 1,
    correct_answer: "Paul",
    explanation: "Saul encountered the risen Jesus and later became widely known as Paul in his ministry.",
    scripture_references: ["Acts 13:9"],
    category: "Early church",
    difficulty: "easy",
  },
  {
    question: "Where were believers first called Christians?",
    options: ["Jerusalem", "Antioch", "Rome", "Corinth"],
    correct_option_index: 1,
    correct_answer: "Antioch",
    explanation: "Acts records that the disciples were first called Christians in Antioch.",
    scripture_references: ["Acts 11:26"],
    category: "Early church",
    difficulty: "medium",
  },
  {
    question: "Who was the first Christian martyr recorded in Acts?",
    options: ["Stephen", "James", "Peter", "Philip"],
    correct_option_index: 0,
    correct_answer: "Stephen",
    explanation: "Stephen testified before the council and was stoned, becoming the first recorded martyr in Acts.",
    scripture_references: ["Acts 7:54-60"],
    category: "Early church",
    difficulty: "medium",
  },
  {
    question: "Which couple lied about the money from a sold property?",
    options: ["Aquila and Priscilla", "Ananias and Sapphira", "Mary and Joseph", "Zechariah and Elizabeth"],
    correct_option_index: 1,
    correct_answer: "Ananias and Sapphira",
    explanation: "They pretended to give the full amount while keeping back part of the proceeds.",
    scripture_references: ["Acts 5:1-10"],
    category: "Early church",
    difficulty: "medium",
  },
  {
    question: "Which book contains the line, 'The Lord is my shepherd'?",
    options: ["Proverbs", "Psalms", "Isaiah", "Romans"],
    correct_option_index: 1,
    correct_answer: "Psalms",
    explanation: "Psalm 23 opens with the well-known confession of the Lord as shepherd.",
    scripture_references: ["Psalms 23:1"],
    category: "Bible books",
    difficulty: "easy",
  },
  {
    question: "Which commandment tells God's people to honor father and mother?",
    options: ["The fifth commandment", "The second commandment", "The seventh commandment", "The tenth commandment"],
    correct_option_index: 0,
    correct_answer: "The fifth commandment",
    explanation: "The command to honor father and mother appears after the commands about worshiping God.",
    scripture_references: ["Exodus 20:12"],
    category: "Law",
    difficulty: "easy",
  },
  {
    question: "Who said, 'As for me and my house, we will serve the Lord'?",
    options: ["Moses", "Joshua", "Samuel", "David"],
    correct_option_index: 1,
    correct_answer: "Joshua",
    explanation: "Joshua called Israel to choose whom they would serve and declared his household's loyalty to the Lord.",
    scripture_references: ["Joshua 24:15"],
    category: "Faithfulness",
    difficulty: "medium",
  },
  {
    question: "Which prophet was taken up by a whirlwind into heaven?",
    options: ["Elijah", "Elisha", "Isaiah", "Jeremiah"],
    correct_option_index: 0,
    correct_answer: "Elijah",
    explanation: "Elijah was taken up as Elisha watched and received his mantle.",
    scripture_references: ["2 Kings 2:11-13"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "What did Ruth say to Naomi about Naomi's God?",
    options: ["Your God will be my God", "Your God has forgotten us", "Your God is hidden", "Your God is far away"],
    correct_option_index: 0,
    correct_answer: "Your God will be my God",
    explanation: "Ruth pledged loyalty to Naomi and to the God Naomi worshiped.",
    scripture_references: ["Ruth 1:16"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "Which queen risked her life to plead for her people?",
    options: ["Vashti", "Jezebel", "Esther", "Athaliah"],
    correct_option_index: 2,
    correct_answer: "Esther",
    explanation: "Esther approached the king to plead for the Jews when their lives were threatened.",
    scripture_references: ["Esther 4:14-16"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "Who rebuilt Jerusalem's wall with the people after exile?",
    options: ["Ezra", "Nehemiah", "Haggai", "Malachi"],
    correct_option_index: 1,
    correct_answer: "Nehemiah",
    explanation: "Nehemiah led the effort to rebuild Jerusalem's walls despite opposition.",
    scripture_references: ["Nehemiah 6:15-16"],
    category: "Old Testament",
    difficulty: "medium",
  },
  {
    question: "Which prophet called fire from heaven on Mount Carmel?",
    options: ["Elisha", "Elijah", "Nathan", "Habakkuk"],
    correct_option_index: 1,
    correct_answer: "Elijah",
    explanation: "Elijah prayed and the Lord answered by fire before the people on Mount Carmel.",
    scripture_references: ["1 Kings 18:36-39"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "Who was placed in a basket and drawn from the Nile as a baby?",
    options: ["Moses", "Samuel", "Isaac", "Benjamin"],
    correct_option_index: 0,
    correct_answer: "Moses",
    explanation: "Pharaoh's daughter found the child in the basket among the reeds of the Nile.",
    scripture_references: ["Exodus 2:3-10"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which priest heard Hannah's prayer in the tabernacle?",
    options: ["Eli", "Aaron", "Zadok", "Melchizedek"],
    correct_option_index: 0,
    correct_answer: "Eli",
    explanation: "Eli saw Hannah praying and later blessed her petition.",
    scripture_references: ["1 Samuel 1:12-17"],
    category: "Prayer",
    difficulty: "medium",
  },
  {
    question: "Who heard God calling his name while serving under Eli?",
    options: ["Samuel", "Saul", "David", "Jonathan"],
    correct_option_index: 0,
    correct_answer: "Samuel",
    explanation: "Samuel learned to answer the Lord's call while serving in the house of God.",
    scripture_references: ["1 Samuel 3:4-10"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which king saw handwriting on the wall during a feast?",
    options: ["Nebuchadnezzar", "Belshazzar", "Darius", "Cyrus"],
    correct_option_index: 1,
    correct_answer: "Belshazzar",
    explanation: "Daniel interpreted the writing as judgment against Belshazzar's kingdom.",
    scripture_references: ["Daniel 5:1-28"],
    category: "Old Testament",
    difficulty: "medium",
  },
  {
    question: "Who was commanded to marry Gomer as a sign to Israel?",
    options: ["Hosea", "Joel", "Amos", "Micah"],
    correct_option_index: 0,
    correct_answer: "Hosea",
    explanation: "Hosea's marriage became a prophetic picture of God's covenant love toward unfaithful Israel.",
    scripture_references: ["Hosea 1:2-3"],
    category: "Prophets",
    difficulty: "hard",
  },
  {
    question: "Which prophet said a child would be called Immanuel?",
    options: ["Isaiah", "Jeremiah", "Ezekiel", "Malachi"],
    correct_option_index: 0,
    correct_answer: "Isaiah",
    explanation: "Isaiah gave the sign of Immanuel, meaning God with us.",
    scripture_references: ["Isaiah 7:14"],
    category: "Prophecy",
    difficulty: "medium",
  },
  {
    question: "Who prepared the way for the Lord according to the Gospels?",
    options: ["John the Baptist", "Simeon", "Joseph", "Andrew"],
    correct_option_index: 0,
    correct_answer: "John the Baptist",
    explanation: "The Gospels connect John's ministry with the voice preparing the way of the Lord.",
    scripture_references: ["Mark 1:2-4"],
    category: "Jesus",
    difficulty: "easy",
  },
  {
    question: "Which tax collector hosted Jesus and then promised restitution?",
    options: ["Matthew", "Zacchaeus", "Levi's father", "Nicodemus"],
    correct_option_index: 1,
    correct_answer: "Zacchaeus",
    explanation: "Zacchaeus received Jesus joyfully and pledged to give generously and repay wrongs.",
    scripture_references: ["Luke 19:8-10"],
    category: "Repentance",
    difficulty: "medium",
  },
  {
    question: "Which sisters hosted Jesus in Bethany?",
    options: ["Mary and Martha", "Rachel and Leah", "Lois and Eunice", "Euodia and Syntyche"],
    correct_option_index: 0,
    correct_answer: "Mary and Martha",
    explanation: "Mary listened at Jesus' feet while Martha served and spoke with Him.",
    scripture_references: ["Luke 10:38-42"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Who was raised from the dead after four days in the tomb?",
    options: ["Lazarus", "Jairus's daughter", "Eutychus", "Tabitha"],
    correct_option_index: 0,
    correct_answer: "Lazarus",
    explanation: "Jesus called Lazarus out of the tomb, revealing His authority over death.",
    scripture_references: ["John 11:38-44"],
    category: "Miracles",
    difficulty: "easy",
  },
  {
    question: "Which disciple walked on water toward Jesus before becoming afraid?",
    options: ["John", "Peter", "Andrew", "Thomas"],
    correct_option_index: 1,
    correct_answer: "Peter",
    explanation: "Peter stepped out of the boat at Jesus' command but began to sink when he saw the wind.",
    scripture_references: ["Matthew 14:28-31"],
    category: "Faith",
    difficulty: "easy",
  },
  {
    question: "Who carried Jesus' cross on the way to Golgotha?",
    options: ["Simon of Cyrene", "Joseph of Arimathea", "Nicodemus", "Barabbas"],
    correct_option_index: 0,
    correct_answer: "Simon of Cyrene",
    explanation: "The soldiers compelled Simon of Cyrene to carry the cross behind Jesus.",
    scripture_references: ["Luke 23:26"],
    category: "Crucifixion",
    difficulty: "medium",
  },
  {
    question: "Who requested Jesus' body for burial?",
    options: ["Joseph of Arimathea", "Caiaphas", "Herod", "Pilate's wife"],
    correct_option_index: 0,
    correct_answer: "Joseph of Arimathea",
    explanation: "Joseph went to Pilate and asked for Jesus' body after the crucifixion.",
    scripture_references: ["Mark 15:43-46"],
    category: "Crucifixion",
    difficulty: "medium",
  },
  {
    question: "Which women first found the stone rolled away in Luke's account?",
    options: ["Mary Magdalene, Joanna, and Mary the mother of James", "Martha and Mary of Bethany", "Priscilla and Lydia", "Ruth and Naomi"],
    correct_option_index: 0,
    correct_answer: "Mary Magdalene, Joanna, and Mary the mother of James",
    explanation: "Luke names these women among those who reported the empty tomb to the apostles.",
    scripture_references: ["Luke 24:10"],
    category: "Resurrection",
    difficulty: "hard",
  },
  {
    question: "What happened when the Holy Spirit came at Pentecost?",
    options: ["Believers spoke in other tongues", "The temple veil tore again", "The Jordan stopped flowing", "The walls of Jerusalem fell"],
    correct_option_index: 0,
    correct_answer: "Believers spoke in other tongues",
    explanation: "The Spirit filled the believers and they began speaking in other tongues as the Spirit enabled them.",
    scripture_references: ["Acts 2:1-4"],
    category: "Holy Spirit",
    difficulty: "easy",
  },
  {
    question: "Who explained the Ethiopian official's reading from Isaiah?",
    options: ["Philip", "Peter", "Stephen", "Barnabas"],
    correct_option_index: 0,
    correct_answer: "Philip",
    explanation: "Philip joined the chariot and proclaimed Jesus from the Scripture the official was reading.",
    scripture_references: ["Acts 8:30-35"],
    category: "Evangelism",
    difficulty: "medium",
  },
  {
    question: "Who opened her home after receiving Paul's message in Philippi?",
    options: ["Lydia", "Phoebe", "Junia", "Chloe"],
    correct_option_index: 0,
    correct_answer: "Lydia",
    explanation: "The Lord opened Lydia's heart, and she and her household were baptized.",
    scripture_references: ["Acts 16:14-15"],
    category: "Early church",
    difficulty: "medium",
  },
  {
    question: "Which jailer asked Paul and Silas what he must do to be saved?",
    options: ["The Philippian jailer", "The Roman centurion", "The temple guard", "The synagogue ruler"],
    correct_option_index: 0,
    correct_answer: "The Philippian jailer",
    explanation: "After the earthquake in Philippi, the jailer asked Paul and Silas about salvation.",
    scripture_references: ["Acts 16:29-31"],
    category: "Salvation",
    difficulty: "medium",
  },
  {
    question: "Which chapter describes love as patient and kind?",
    options: ["1 Corinthians 13", "Romans 8", "Hebrews 11", "James 2"],
    correct_option_index: 0,
    correct_answer: "1 Corinthians 13",
    explanation: "Paul describes the character of love in 1 Corinthians 13.",
    scripture_references: ["1 Corinthians 13:4"],
    category: "Christian living",
    difficulty: "easy",
  },
  {
    question: "What does James say faith without works is?",
    options: ["Dead", "Hidden", "Optional", "Complete"],
    correct_option_index: 0,
    correct_answer: "Dead",
    explanation: "James teaches that genuine faith is shown through action.",
    scripture_references: ["James 2:17"],
    category: "Christian living",
    difficulty: "medium",
  },
  {
    question: "Which book emphasizes that Jesus is the Word made flesh?",
    options: ["John", "Mark", "Acts", "Jude"],
    correct_option_index: 0,
    correct_answer: "John",
    explanation: "John opens by identifying the Word with God and later says the Word became flesh.",
    scripture_references: ["John 1:1", "John 1:14"],
    category: "Bible books",
    difficulty: "medium",
  },
  {
    question: "Who wrote to Philemon about receiving Onesimus?",
    options: ["Paul", "Peter", "James", "John"],
    correct_option_index: 0,
    correct_answer: "Paul",
    explanation: "Paul appealed to Philemon to receive Onesimus no longer merely as a slave but as a beloved brother.",
    scripture_references: ["Philemon 1:10-16"],
    category: "Letters",
    difficulty: "hard",
  },
  {
    question: "Which armor piece is called the shield in Ephesians 6?",
    options: ["Faith", "Righteousness", "Salvation", "Truth"],
    correct_option_index: 0,
    correct_answer: "Faith",
    explanation: "Paul tells believers to take up the shield of faith against the flaming darts of the evil one.",
    scripture_references: ["Ephesians 6:16"],
    category: "Christian living",
    difficulty: "medium",
  },
  {
    question: "Which church was told it had left its first love in Revelation?",
    options: ["Ephesus", "Smyrna", "Pergamum", "Laodicea"],
    correct_option_index: 0,
    correct_answer: "Ephesus",
    explanation: "The message to Ephesus commends endurance but warns that they had abandoned their first love.",
    scripture_references: ["Revelation 2:1-4"],
    category: "Revelation",
    difficulty: "hard",
  },
  {
    question: "Who was called a friend of God in James?",
    options: ["Abraham", "Moses", "David", "Job"],
    correct_option_index: 0,
    correct_answer: "Abraham",
    explanation: "James cites Abraham's faith and says he was called the friend of God.",
    scripture_references: ["James 2:23"],
    category: "Faith",
    difficulty: "medium",
  },
  {
    question: "Which man lost his possessions but continued to wrestle honestly with God?",
    options: ["Job", "Boaz", "Caleb", "Lot"],
    correct_option_index: 0,
    correct_answer: "Job",
    explanation: "Job endured severe loss and suffering while the book explores faith, grief, and God's sovereignty.",
    scripture_references: ["Job 1:20-22"],
    category: "Wisdom",
    difficulty: "medium",
  },
  {
    question: "Who said, 'Here am I. Send me' after seeing the Lord?",
    options: ["Isaiah", "Jeremiah", "Ezekiel", "Amos"],
    correct_option_index: 0,
    correct_answer: "Isaiah",
    explanation: "Isaiah responded to God's call after his vision in the temple.",
    scripture_references: ["Isaiah 6:8"],
    category: "Calling",
    difficulty: "medium",
  },
  {
    question: "Which prophet was told before birth that he was appointed to the nations?",
    options: ["Jeremiah", "Daniel", "Joel", "Obadiah"],
    correct_option_index: 0,
    correct_answer: "Jeremiah",
    explanation: "The Lord told Jeremiah He had known and appointed him before birth.",
    scripture_references: ["Jeremiah 1:5"],
    category: "Calling",
    difficulty: "medium",
  },
  {
    question: "What did Jesus say is the greatest commandment?",
    options: ["Love the Lord your God", "Honor the Sabbath only", "Give all possessions away", "Avoid every tax collector"],
    correct_option_index: 0,
    correct_answer: "Love the Lord your God",
    explanation: "Jesus identified loving God with all the heart, soul, and mind as the greatest commandment.",
    scripture_references: ["Matthew 22:37-38"],
    category: "Jesus",
    difficulty: "easy",
  },
  {
    question: "What did Jesus call the second commandment like the first?",
    options: ["Love your neighbor as yourself", "Fast twice a week", "Wash ceremonial cups", "Build larger barns"],
    correct_option_index: 0,
    correct_answer: "Love your neighbor as yourself",
    explanation: "Jesus paired love for neighbor with love for God as the heart of the Law and Prophets.",
    scripture_references: ["Matthew 22:39-40"],
    category: "Christian living",
    difficulty: "easy",
  },
  {
    question: "Which Psalm says God's word is a lamp to the feet?",
    options: ["Psalm 119", "Psalm 1", "Psalm 51", "Psalm 150"],
    correct_option_index: 0,
    correct_answer: "Psalm 119",
    explanation: "Psalm 119 celebrates God's word as guidance for the path of life.",
    scripture_references: ["Psalms 119:105"],
    category: "Wisdom",
    difficulty: "medium",
  },
];
