export type QuizQuestion = {
  question: string;
  options: [string, string, string, string];
  correct_option_index: number;
  correct_answer: string;
  explanation: string;
  scripture_references: string[];
  category: string;
  difficulty: "easy" | "medium" | "hard";
};

export const fallbackQuizQuestions: QuizQuestion[] = [
  {
    question: "Which woman hid two Israelite spies in Jericho?",
    options: ["Rahab", "Deborah", "Ruth", "Miriam"],
    correct_option_index: 0,
    correct_answer: "Rahab",
    explanation: "Rahab protected the spies before Israel entered the land, and they promised mercy to her household.",
    scripture_references: ["Joshua 2:1-14"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which disciple asked to see the nail marks before believing Jesus had risen?",
    options: ["Andrew", "Thomas", "Philip", "James"],
    correct_option_index: 1,
    correct_answer: "Thomas",
    explanation: "Thomas was absent when Jesus first appeared to the disciples and later confessed faith after seeing Him.",
    scripture_references: ["John 20:24-29"],
    category: "Resurrection",
    difficulty: "easy",
  },
  {
    question: "What did God provide each morning for Israel in the wilderness?",
    options: ["Olives", "Manna", "Grapes", "Honey"],
    correct_option_index: 1,
    correct_answer: "Manna",
    explanation: "The Lord provided manna daily as bread from heaven for Israel during their journey.",
    scripture_references: ["Exodus 16:13-18"],
    category: "Wilderness",
    difficulty: "easy",
  },
  {
    question: "Who interpreted Pharaoh's dreams in Egypt?",
    options: ["Joseph", "Moses", "Daniel", "Samuel"],
    correct_option_index: 0,
    correct_answer: "Joseph",
    explanation: "Joseph told Pharaoh that God had revealed the coming years of plenty and famine.",
    scripture_references: ["Genesis 41:14-32"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "Which judge led Israel after hearing from the prophetess Deborah?",
    options: ["Gideon", "Barak", "Samson", "Ehud"],
    correct_option_index: 1,
    correct_answer: "Barak",
    explanation: "Deborah summoned Barak and gave him the Lord's command concerning Sisera.",
    scripture_references: ["Judges 4:4-10"],
    category: "Judges",
    difficulty: "medium",
  },
  {
    question: "What object did David use to defeat Goliath?",
    options: ["A spear", "A sling and stone", "A sword", "A bow"],
    correct_option_index: 1,
    correct_answer: "A sling and stone",
    explanation: "David struck Goliath with a stone from his sling and the giant fell.",
    scripture_references: ["1 Samuel 17:49"],
    category: "Bible events",
    difficulty: "easy",
  },
  {
    question: "Who was swallowed by a great fish after fleeing from God's command?",
    options: ["Jonah", "Nahum", "Micah", "Hosea"],
    correct_option_index: 0,
    correct_answer: "Jonah",
    explanation: "Jonah ran from the mission to Nineveh, and the Lord appointed a great fish to swallow him.",
    scripture_references: ["Jonah 1:17"],
    category: "Prophets",
    difficulty: "easy",
  },
  {
    question: "Which city did God spare after its people repented at Jonah's preaching?",
    options: ["Babylon", "Nineveh", "Jericho", "Tyre"],
    correct_option_index: 1,
    correct_answer: "Nineveh",
    explanation: "Nineveh believed God, turned from evil, and God showed mercy.",
    scripture_references: ["Jonah 3:5-10"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "Who asked God for wisdom to govern the people?",
    options: ["Saul", "Solomon", "Hezekiah", "Josiah"],
    correct_option_index: 1,
    correct_answer: "Solomon",
    explanation: "Solomon asked for an understanding heart, and God was pleased with his request.",
    scripture_references: ["1 Kings 3:7-12"],
    category: "Kings",
    difficulty: "easy",
  },
  {
    question: "Which prophet saw dry bones come to life in a vision?",
    options: ["Isaiah", "Ezekiel", "Jeremiah", "Amos"],
    correct_option_index: 1,
    correct_answer: "Ezekiel",
    explanation: "Ezekiel saw a valley of dry bones restored as a sign of God's power to revive Israel.",
    scripture_references: ["Ezekiel 37:1-10"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "Who baptized Jesus in the Jordan River?",
    options: ["Peter", "John the Baptist", "James", "Philip"],
    correct_option_index: 1,
    correct_answer: "John the Baptist",
    explanation: "Jesus came to John at the Jordan to be baptized before beginning His public ministry.",
    scripture_references: ["Matthew 3:13-17"],
    category: "Jesus",
    difficulty: "easy",
  },
  {
    question: "What did Jesus turn into wine at Cana?",
    options: ["Oil", "Milk", "Water", "Vinegar"],
    correct_option_index: 2,
    correct_answer: "Water",
    explanation: "At the wedding in Cana, Jesus changed water into wine as His first recorded sign in John.",
    scripture_references: ["John 2:1-11"],
    category: "Jesus",
    difficulty: "easy",
  },
  {
    question: "Which parable tells of a son who wasted his inheritance and returned home?",
    options: ["The Good Samaritan", "The Prodigal Son", "The Sower", "The Talents"],
    correct_option_index: 1,
    correct_answer: "The Prodigal Son",
    explanation: "Jesus told of a lost son welcomed by his father to show mercy and restoration.",
    scripture_references: ["Luke 15:11-24"],
    category: "Parables",
    difficulty: "easy",
  },
  {
    question: "Who climbed a sycamore tree to see Jesus?",
    options: ["Zacchaeus", "Nicodemus", "Bartimaeus", "Jairus"],
    correct_option_index: 0,
    correct_answer: "Zacchaeus",
    explanation: "Zacchaeus climbed the tree because he was short and wanted to see Jesus passing by.",
    scripture_references: ["Luke 19:1-6"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which apostle was formerly known as Saul of Tarsus?",
    options: ["Peter", "Paul", "Barnabas", "Silas"],
    correct_option_index: 1,
    correct_answer: "Paul",
    explanation: "Saul encountered the risen Jesus and later became widely known as Paul in his ministry.",
    scripture_references: ["Acts 13:9"],
    category: "Early church",
    difficulty: "easy",
  },
  {
    question: "Where were believers first called Christians?",
    options: ["Jerusalem", "Antioch", "Rome", "Corinth"],
    correct_option_index: 1,
    correct_answer: "Antioch",
    explanation: "Acts records that the disciples were first called Christians in Antioch.",
    scripture_references: ["Acts 11:26"],
    category: "Early church",
    difficulty: "medium",
  },
  {
    question: "Who was the first Christian martyr recorded in Acts?",
    options: ["Stephen", "James", "Peter", "Philip"],
    correct_option_index: 0,
    correct_answer: "Stephen",
    explanation: "Stephen testified before the council and was stoned, becoming the first recorded martyr in Acts.",
    scripture_references: ["Acts 7:54-60"],
    category: "Early church",
    difficulty: "medium",
  },
  {
    question: "Which couple lied about the money from a sold property?",
    options: ["Aquila and Priscilla", "Ananias and Sapphira", "Mary and Joseph", "Zechariah and Elizabeth"],
    correct_option_index: 1,
    correct_answer: "Ananias and Sapphira",
    explanation: "They pretended to give the full amount while keeping back part of the proceeds.",
    scripture_references: ["Acts 5:1-10"],
    category: "Early church",
    difficulty: "medium",
  },
  {
    question: "Which book contains the line, 'The Lord is my shepherd'?",
    options: ["Proverbs", "Psalms", "Isaiah", "Romans"],
    correct_option_index: 1,
    correct_answer: "Psalms",
    explanation: "Psalm 23 opens with the well-known confession of the Lord as shepherd.",
    scripture_references: ["Psalms 23:1"],
    category: "Bible books",
    difficulty: "easy",
  },
  {
    question: "Which commandment tells God's people to honor father and mother?",
    options: ["The fifth commandment", "The second commandment", "The seventh commandment", "The tenth commandment"],
    correct_option_index: 0,
    correct_answer: "The fifth commandment",
    explanation: "The command to honor father and mother appears after the commands about worshiping God.",
    scripture_references: ["Exodus 20:12"],
    category: "Law",
    difficulty: "easy",
  },
  {
    question: "Who said, 'As for me and my house, we will serve the Lord'?",
    options: ["Moses", "Joshua", "Samuel", "David"],
    correct_option_index: 1,
    correct_answer: "Joshua",
    explanation: "Joshua called Israel to choose whom they would serve and declared his household's loyalty to the Lord.",
    scripture_references: ["Joshua 24:15"],
    category: "Faithfulness",
    difficulty: "medium",
  },
  {
    question: "Which prophet was taken up by a whirlwind into heaven?",
    options: ["Elijah", "Elisha", "Isaiah", "Jeremiah"],
    correct_option_index: 0,
    correct_answer: "Elijah",
    explanation: "Elijah was taken up as Elisha watched and received his mantle.",
    scripture_references: ["2 Kings 2:11-13"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "What did Ruth say to Naomi about Naomi's God?",
    options: ["Your God will be my God", "Your God has forgotten us", "Your God is hidden", "Your God is far away"],
    correct_option_index: 0,
    correct_answer: "Your God will be my God",
    explanation: "Ruth pledged loyalty to Naomi and to the God Naomi worshiped.",
    scripture_references: ["Ruth 1:16"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "Which queen risked her life to plead for her people?",
    options: ["Vashti", "Jezebel", "Esther", "Athaliah"],
    correct_option_index: 2,
    correct_answer: "Esther",
    explanation: "Esther approached the king to plead for the Jews when their lives were threatened.",
    scripture_references: ["Esther 4:14-16"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "Who rebuilt Jerusalem's wall with the people after exile?",
    options: ["Ezra", "Nehemiah", "Haggai", "Malachi"],
    correct_option_index: 1,
    correct_answer: "Nehemiah",
    explanation: "Nehemiah led the effort to rebuild Jerusalem's walls despite opposition.",
    scripture_references: ["Nehemiah 6:15-16"],
    category: "Old Testament",
    difficulty: "medium",
  },
  {
    question: "Which prophet called fire from heaven on Mount Carmel?",
    options: ["Elisha", "Elijah", "Nathan", "Habakkuk"],
    correct_option_index: 1,
    correct_answer: "Elijah",
    explanation: "Elijah prayed and the Lord answered by fire before the people on Mount Carmel.",
    scripture_references: ["1 Kings 18:36-39"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "Who was placed in a basket and drawn from the Nile as a baby?",
    options: ["Moses", "Samuel", "Isaac", "Benjamin"],
    correct_option_index: 0,
    correct_answer: "Moses",
    explanation: "Pharaoh's daughter found the child in the basket among the reeds of the Nile.",
    scripture_references: ["Exodus 2:3-10"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which priest heard Hannah's prayer in the tabernacle?",
    options: ["Eli", "Aaron", "Zadok", "Melchizedek"],
    correct_option_index: 0,
    correct_answer: "Eli",
    explanation: "Eli saw Hannah praying and later blessed her petition.",
    scripture_references: ["1 Samuel 1:12-17"],
    category: "Prayer",
    difficulty: "medium",
  },
  {
    question: "Who heard God calling his name while serving under Eli?",
    options: ["Samuel", "Saul", "David", "Jonathan"],
    correct_option_index: 0,
    correct_answer: "Samuel",
    explanation: "Samuel learned to answer the Lord's call while serving in the house of God.",
    scripture_references: ["1 Samuel 3:4-10"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which king saw handwriting on the wall during a feast?",
    options: ["Nebuchadnezzar", "Belshazzar", "Darius", "Cyrus"],
    correct_option_index: 1,
    correct_answer: "Belshazzar",
    explanation: "Daniel interpreted the writing as judgment against Belshazzar's kingdom.",
    scripture_references: ["Daniel 5:1-28"],
    category: "Old Testament",
    difficulty: "medium",
  },
  {
    question: "Who was commanded to marry Gomer as a sign to Israel?",
    options: ["Hosea", "Joel", "Amos", "Micah"],
    correct_option_index: 0,
    correct_answer: "Hosea",
    explanation: "Hosea's marriage became a prophetic picture of God's covenant love toward unfaithful Israel.",
    scripture_references: ["Hosea 1:2-3"],
    category: "Prophets",
    difficulty: "hard",
  },
  {
    question: "Which prophet said a child would be called Immanuel?",
    options: ["Isaiah", "Jeremiah", "Ezekiel", "Malachi"],
    correct_option_index: 0,
    correct_answer: "Isaiah",
    explanation: "Isaiah gave the sign of Immanuel, meaning God with us.",
    scripture_references: ["Isaiah 7:14"],
    category: "Prophecy",
    difficulty: "medium",
  },
  {
    question: "Who prepared the way for the Lord according to the Gospels?",
    options: ["John the Baptist", "Simeon", "Joseph", "Andrew"],
    correct_option_index: 0,
    correct_answer: "John the Baptist",
    explanation: "The Gospels connect John's ministry with the voice preparing the way of the Lord.",
    scripture_references: ["Mark 1:2-4"],
    category: "Jesus",
    difficulty: "easy",
  },
  {
    question: "Which tax collector hosted Jesus and then promised restitution?",
    options: ["Matthew", "Zacchaeus", "Levi's father", "Nicodemus"],
    correct_option_index: 1,
    correct_answer: "Zacchaeus",
    explanation: "Zacchaeus received Jesus joyfully and pledged to give generously and repay wrongs.",
    scripture_references: ["Luke 19:8-10"],
    category: "Repentance",
    difficulty: "medium",
  },
  {
    question: "Which sisters hosted Jesus in Bethany?",
    options: ["Mary and Martha", "Rachel and Leah", "Lois and Eunice", "Euodia and Syntyche"],
    correct_option_index: 0,
    correct_answer: "Mary and Martha",
    explanation: "Mary listened at Jesus' feet while Martha served and spoke with Him.",
    scripture_references: ["Luke 10:38-42"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Who was raised from the dead after four days in the tomb?",
    options: ["Lazarus", "Jairus's daughter", "Eutychus", "Tabitha"],
    correct_option_index: 0,
    correct_answer: "Lazarus",
    explanation: "Jesus called Lazarus out of the tomb, revealing His authority over death.",
    scripture_references: ["John 11:38-44"],
    category: "Miracles",
    difficulty: "easy",
  },
  {
    question: "Which disciple walked on water toward Jesus before becoming afraid?",
    options: ["John", "Peter", "Andrew", "Thomas"],
    correct_option_index: 1,
    correct_answer: "Peter",
    explanation: "Peter stepped out of the boat at Jesus' command but began to sink when he saw the wind.",
    scripture_references: ["Matthew 14:28-31"],
    category: "Faith",
    difficulty: "easy",
  },
  {
    question: "Who carried Jesus' cross on the way to Golgotha?",
    options: ["Simon of Cyrene", "Joseph of Arimathea", "Nicodemus", "Barabbas"],
    correct_option_index: 0,
    correct_answer: "Simon of Cyrene",
    explanation: "The soldiers compelled Simon of Cyrene to carry the cross behind Jesus.",
    scripture_references: ["Luke 23:26"],
    category: "Crucifixion",
    difficulty: "medium",
  },
  {
    question: "Who requested Jesus' body for burial?",
    options: ["Joseph of Arimathea", "Caiaphas", "Herod", "Pilate's wife"],
    correct_option_index: 0,
    correct_answer: "Joseph of Arimathea",
    explanation: "Joseph went to Pilate and asked for Jesus' body after the crucifixion.",
    scripture_references: ["Mark 15:43-46"],
    category: "Crucifixion",
    difficulty: "medium",
  },
  {
    question: "Which women first found the stone rolled away in Luke's account?",
    options: ["Mary Magdalene, Joanna, and Mary the mother of James", "Martha and Mary of Bethany", "Priscilla and Lydia", "Ruth and Naomi"],
    correct_option_index: 0,
    correct_answer: "Mary Magdalene, Joanna, and Mary the mother of James",
    explanation: "Luke names these women among those who reported the empty tomb to the apostles.",
    scripture_references: ["Luke 24:10"],
    category: "Resurrection",
    difficulty: "hard",
  },
  {
    question: "What happened when the Holy Spirit came at Pentecost?",
    options: ["Believers spoke in other tongues", "The temple veil tore again", "The Jordan stopped flowing", "The walls of Jerusalem fell"],
    correct_option_index: 0,
    correct_answer: "Believers spoke in other tongues",
    explanation: "The Spirit filled the believers and they began speaking in other tongues as the Spirit enabled them.",
    scripture_references: ["Acts 2:1-4"],
    category: "Holy Spirit",
    difficulty: "easy",
  },
  {
    question: "Who explained the Ethiopian official's reading from Isaiah?",
    options: ["Philip", "Peter", "Stephen", "Barnabas"],
    correct_option_index: 0,
    correct_answer: "Philip",
    explanation: "Philip joined the chariot and proclaimed Jesus from the Scripture the official was reading.",
    scripture_references: ["Acts 8:30-35"],
    category: "Evangelism",
    difficulty: "medium",
  },
  {
    question: "Who opened her home after receiving Paul's message in Philippi?",
    options: ["Lydia", "Phoebe", "Junia", "Chloe"],
    correct_option_index: 0,
    correct_answer: "Lydia",
    explanation: "The Lord opened Lydia's heart, and she and her household were baptized.",
    scripture_references: ["Acts 16:14-15"],
    category: "Early church",
    difficulty: "medium",
  },
  {
    question: "Which jailer asked Paul and Silas what he must do to be saved?",
    options: ["The Philippian jailer", "The Roman centurion", "The temple guard", "The synagogue ruler"],
    correct_option_index: 0,
    correct_answer: "The Philippian jailer",
    explanation: "After the earthquake in Philippi, the jailer asked Paul and Silas about salvation.",
    scripture_references: ["Acts 16:29-31"],
    category: "Salvation",
    difficulty: "medium",
  },
  {
    question: "Which chapter describes love as patient and kind?",
    options: ["1 Corinthians 13", "Romans 8", "Hebrews 11", "James 2"],
    correct_option_index: 0,
    correct_answer: "1 Corinthians 13",
    explanation: "Paul describes the character of love in 1 Corinthians 13.",
    scripture_references: ["1 Corinthians 13:4"],
    category: "Christian living",
    difficulty: "easy",
  },
  {
    question: "What does James say faith without works is?",
    options: ["Dead", "Hidden", "Optional", "Complete"],
    correct_option_index: 0,
    correct_answer: "Dead",
    explanation: "James teaches that genuine faith is shown through action.",
    scripture_references: ["James 2:17"],
    category: "Christian living",
    difficulty: "medium",
  },
  {
    question: "Which book emphasizes that Jesus is the Word made flesh?",
    options: ["John", "Mark", "Acts", "Jude"],
    correct_option_index: 0,
    correct_answer: "John",
    explanation: "John opens by identifying the Word with God and later says the Word became flesh.",
    scripture_references: ["John 1:1", "John 1:14"],
    category: "Bible books",
    difficulty: "medium",
  },
  {
    question: "Who wrote to Philemon about receiving Onesimus?",
    options: ["Paul", "Peter", "James", "John"],
    correct_option_index: 0,
    correct_answer: "Paul",
    explanation: "Paul appealed to Philemon to receive Onesimus no longer merely as a slave but as a beloved brother.",
    scripture_references: ["Philemon 1:10-16"],
    category: "Letters",
    difficulty: "hard",
  },
  {
    question: "Which armor piece is called the shield in Ephesians 6?",
    options: ["Faith", "Righteousness", "Salvation", "Truth"],
    correct_option_index: 0,
    correct_answer: "Faith",
    explanation: "Paul tells believers to take up the shield of faith against the flaming darts of the evil one.",
    scripture_references: ["Ephesians 6:16"],
    category: "Christian living",
    difficulty: "medium",
  },
  {
    question: "Which church was told it had left its first love in Revelation?",
    options: ["Ephesus", "Smyrna", "Pergamum", "Laodicea"],
    correct_option_index: 0,
    correct_answer: "Ephesus",
    explanation: "The message to Ephesus commends endurance but warns that they had abandoned their first love.",
    scripture_references: ["Revelation 2:1-4"],
    category: "Revelation",
    difficulty: "hard",
  },
  {
    question: "Who was called a friend of God in James?",
    options: ["Abraham", "Moses", "David", "Job"],
    correct_option_index: 0,
    correct_answer: "Abraham",
    explanation: "James cites Abraham's faith and says he was called the friend of God.",
    scripture_references: ["James 2:23"],
    category: "Faith",
    difficulty: "medium",
  },
  {
    question: "Which man lost his possessions but continued to wrestle honestly with God?",
    options: ["Job", "Boaz", "Caleb", "Lot"],
    correct_option_index: 0,
    correct_answer: "Job",
    explanation: "Job endured severe loss and suffering while the book explores faith, grief, and God's sovereignty.",
    scripture_references: ["Job 1:20-22"],
    category: "Wisdom",
    difficulty: "medium",
  },
  {
    question: "Who said, 'Here am I. Send me' after seeing the Lord?",
    options: ["Isaiah", "Jeremiah", "Ezekiel", "Amos"],
    correct_option_index: 0,
    correct_answer: "Isaiah",
    explanation: "Isaiah responded to God's call after his vision in the temple.",
    scripture_references: ["Isaiah 6:8"],
    category: "Calling",
    difficulty: "medium",
  },
  {
    question: "Which prophet was told before birth that he was appointed to the nations?",
    options: ["Jeremiah", "Daniel", "Joel", "Obadiah"],
    correct_option_index: 0,
    correct_answer: "Jeremiah",
    explanation: "The Lord told Jeremiah He had known and appointed him before birth.",
    scripture_references: ["Jeremiah 1:5"],
    category: "Calling",
    difficulty: "medium",
  },
  {
    question: "What did Jesus say is the greatest commandment?",
    options: ["Love the Lord your God", "Honor the Sabbath only", "Give all possessions away", "Avoid every tax collector"],
    correct_option_index: 0,
    correct_answer: "Love the Lord your God",
    explanation: "Jesus identified loving God with all the heart, soul, and mind as the greatest commandment.",
    scripture_references: ["Matthew 22:37-38"],
    category: "Jesus",
    difficulty: "easy",
  },
  {
    question: "What did Jesus call the second commandment like the first?",
    options: ["Love your neighbor as yourself", "Fast twice a week", "Wash ceremonial cups", "Build larger barns"],
    correct_option_index: 0,
    correct_answer: "Love your neighbor as yourself",
    explanation: "Jesus paired love for neighbor with love for God as the heart of the Law and Prophets.",
    scripture_references: ["Matthew 22:39-40"],
    category: "Christian living",
    difficulty: "easy",
  },
  {
    question: "Which Psalm says God's word is a lamp to the feet?",
    options: ["Psalm 119", "Psalm 1", "Psalm 51", "Psalm 150"],
    correct_option_index: 0,
    correct_answer: "Psalm 119",
    explanation: "Psalm 119 celebrates God's word as guidance for the path of life.",
    scripture_references: ["Psalms 119:105"],
    category: "Wisdom",
    difficulty: "medium",
  },

  // The block below is a manually curated, verified expansion added as a
  // resilience backup: if the AI provider is unavailable or over quota (as
  // happened in production), a pop-quiz day can still draw from this bank
  // instead of publishing nothing. Every reference below was checked by
  // hand against the actual passage, not just carried over from the source
  // trivia list unverified.
  {
    question: "In what city was Jesus born?",
    options: ["Bethlehem", "Nazareth", "Jerusalem", "Capernaum"],
    correct_option_index: 0,
    correct_answer: "Bethlehem",
    explanation: "Jesus was born in Bethlehem in Judea, fulfilling the prophecy of Micah 5:2.",
    scripture_references: ["Luke 2:4-7"],
    category: "Nativity",
    difficulty: "easy",
  },
  {
    question: "What did John the Baptist eat in the desert?",
    options: ["Locusts and wild honey", "Manna", "Bread and fish", "Grapes and figs"],
    correct_option_index: 0,
    correct_answer: "Locusts and wild honey",
    explanation: "John's clothing and diet in the wilderness marked him as a prophet in the mold of Elijah.",
    scripture_references: ["Matthew 3:4"],
    category: "New Testament",
    difficulty: "easy",
  },
  {
    question: "Which two brothers were the first disciples Jesus called?",
    options: ["Peter and Andrew", "James and John", "Philip and Bartholomew", "Thomas and Matthew"],
    correct_option_index: 0,
    correct_answer: "Peter and Andrew",
    explanation: "Jesus found the two brothers fishing on the Sea of Galilee and called them to follow Him.",
    scripture_references: ["Matthew 4:18-20"],
    category: "Apostles",
    difficulty: "easy",
  },
  {
    question: "How many times did Peter deny knowing Jesus on the night of His arrest?",
    options: ["Three times", "Once", "Twice", "Four times"],
    correct_option_index: 0,
    correct_answer: "Three times",
    explanation: "Just as Jesus foretold, Peter denied Him three times before the rooster crowed.",
    scripture_references: ["Matthew 26:34", "Matthew 26:69-75"],
    category: "Apostles",
    difficulty: "easy",
  },
  {
    question: "Who recognized Jesus as the Messiah when He was presented at the Temple as a baby?",
    options: ["Simeon", "Zechariah", "Nicodemus", "Gamaliel"],
    correct_option_index: 0,
    correct_answer: "Simeon",
    explanation: "Simeon had been promised he would not die before seeing the Lord's Messiah.",
    scripture_references: ["Luke 2:25-35"],
    category: "Nativity",
    difficulty: "medium",
  },
  {
    question: "Who asked Pilate for Jesus' body after the crucifixion?",
    options: ["Joseph of Arimathea", "Nicodemus", "Simon of Cyrene", "Barnabas"],
    correct_option_index: 0,
    correct_answer: "Joseph of Arimathea",
    explanation: "Joseph, a rich man and secret disciple, asked for the body and laid it in his own new tomb.",
    scripture_references: ["Matthew 27:57-60"],
    category: "Crucifixion",
    difficulty: "medium",
  },
  {
    question: "On what island was Paul shipwrecked on his way to Rome?",
    options: ["Malta", "Crete", "Cyprus", "Rhodes"],
    correct_option_index: 0,
    correct_answer: "Malta",
    explanation: "After the storm and shipwreck, the islanders of Malta showed Paul and the crew unusual kindness.",
    scripture_references: ["Acts 28:1"],
    category: "Paul's journeys",
    difficulty: "medium",
  },
  {
    question: "Who wrote the Book of Revelation?",
    options: ["John", "Paul", "Peter", "Matthew"],
    correct_option_index: 0,
    correct_answer: "John",
    explanation: "John received the revelation while exiled on the island of Patmos.",
    scripture_references: ["Revelation 1:1", "Revelation 1:9"],
    category: "New Testament",
    difficulty: "easy",
  },
  {
    question: "What was Matthew's occupation before Jesus called him?",
    options: ["Tax collector", "Fisherman", "Shepherd", "Physician"],
    correct_option_index: 0,
    correct_answer: "Tax collector",
    explanation: "Jesus called Matthew away from his tax booth to follow Him.",
    scripture_references: ["Matthew 9:9"],
    category: "Apostles",
    difficulty: "easy",
  },
  {
    question: "To what city was Saul traveling when a great light struck him blind?",
    options: ["Damascus", "Jerusalem", "Antioch", "Tarsus"],
    correct_option_index: 0,
    correct_answer: "Damascus",
    explanation: "Saul was on the road to Damascus, intending to arrest believers, when Jesus confronted him.",
    scripture_references: ["Acts 9:3-4"],
    category: "Paul's journeys",
    difficulty: "easy",
  },
  {
    question: "In the parable of the Good Samaritan, who passed by the injured man first?",
    options: ["A priest", "A Levite", "A Samaritan", "An innkeeper"],
    correct_option_index: 0,
    correct_answer: "A priest",
    explanation: "Both the priest and a Levite passed by before the Samaritan stopped to help.",
    scripture_references: ["Luke 10:31-33"],
    category: "Parables",
    difficulty: "medium",
  },
  {
    question: "From which tribe of Israel did the apostle Paul come?",
    options: ["Benjamin", "Judah", "Levi", "Ephraim"],
    correct_option_index: 0,
    correct_answer: "Benjamin",
    explanation: "Paul identifies himself as a Hebrew of Hebrews, of the tribe of Benjamin.",
    scripture_references: ["Philippians 3:5"],
    category: "Paul's journeys",
    difficulty: "medium",
  },
  {
    question: "Who was the first Christian martyr, stoned to death in Acts?",
    options: ["Stephen", "James", "Barnabas", "Timothy"],
    correct_option_index: 0,
    correct_answer: "Stephen",
    explanation: "Stephen was full of the Spirit and was stoned after his defense before the Sanhedrin.",
    scripture_references: ["Acts 7:54-60"],
    category: "New Testament",
    difficulty: "medium",
  },
  {
    question: "Which high priest presided over Jesus's trial?",
    options: ["Caiaphas", "Annas", "Herod", "Pilate"],
    correct_option_index: 0,
    correct_answer: "Caiaphas",
    explanation: "Jesus was brought before Caiaphas, the high priest, where the Sanhedrin gathered.",
    scripture_references: ["Matthew 26:57"],
    category: "Crucifixion",
    difficulty: "medium",
  },
  {
    question: "Which apostle doubted the resurrection until he could touch Jesus's wounds?",
    options: ["Thomas", "Philip", "Andrew", "Bartholomew"],
    correct_option_index: 0,
    correct_answer: "Thomas",
    explanation: "Thomas declared he would not believe until he saw and touched the wounds himself.",
    scripture_references: ["John 20:24-29"],
    category: "Resurrection",
    difficulty: "easy",
  },
  {
    question: "How did Judas identify Jesus to the arresting officials?",
    options: ["With a kiss", "By pointing", "By calling His name aloud", "With a raised hand"],
    correct_option_index: 0,
    correct_answer: "With a kiss",
    explanation: "Judas had arranged a kiss as the prearranged signal to identify Jesus.",
    scripture_references: ["Matthew 26:48-49"],
    category: "Crucifixion",
    difficulty: "easy",
  },
  {
    question: "Who had John the Baptist beheaded?",
    options: ["Herod Antipas", "Herod the Great", "Pontius Pilate", "Herod Agrippa"],
    correct_option_index: 0,
    correct_answer: "Herod Antipas",
    explanation: "Herod Antipas had John killed after a promise made to Herodias's daughter.",
    scripture_references: ["Mark 6:21-28"],
    category: "New Testament",
    difficulty: "medium",
  },
  {
    question: "Who baptized Jesus in the Jordan River?",
    options: ["John the Baptist", "Peter", "Andrew", "John the Apostle"],
    correct_option_index: 0,
    correct_answer: "John the Baptist",
    explanation: "The Spirit descended like a dove as Jesus came up out of the water.",
    scripture_references: ["Matthew 3:13-17"],
    category: "New Testament",
    difficulty: "easy",
  },
  {
    question: "Which Gospel writer was a physician by trade?",
    options: ["Luke", "Matthew", "Mark", "John"],
    correct_option_index: 0,
    correct_answer: "Luke",
    explanation: "Paul refers to Luke as 'the beloved physician' among his companions.",
    scripture_references: ["Colossians 4:14"],
    category: "New Testament",
    difficulty: "medium",
  },
  {
    question: "On what day of creation did God make man?",
    options: ["The sixth day", "The fifth day", "The seventh day", "The fourth day"],
    correct_option_index: 0,
    correct_answer: "The sixth day",
    explanation: "God formed man from the dust on the sixth day, the same day as the land animals.",
    scripture_references: ["Genesis 1:26-31"],
    category: "Creation",
    difficulty: "easy",
  },
  {
    question: "What was the name of Adam and Eve's third named son?",
    options: ["Seth", "Enosh", "Cain", "Abel"],
    correct_option_index: 0,
    correct_answer: "Seth",
    explanation: "Seth was born to Adam and Eve after Cain killed Abel.",
    scripture_references: ["Genesis 4:25"],
    category: "Creation",
    difficulty: "medium",
  },
  {
    question: "What is the first of the Ten Commandments?",
    options: ["You shall have no other gods before me", "You shall not murder", "Honor your father and mother", "Remember the Sabbath"],
    correct_option_index: 0,
    correct_answer: "You shall have no other gods before me",
    explanation: "The first commandment establishes exclusive devotion to the Lord.",
    scripture_references: ["Exodus 20:3"],
    category: "Exodus",
    difficulty: "easy",
  },
  {
    question: "Who was the mother of the prophet Samuel?",
    options: ["Hannah", "Sarah", "Rebekah", "Elizabeth"],
    correct_option_index: 0,
    correct_answer: "Hannah",
    explanation: "Hannah prayed earnestly for a son and dedicated Samuel to the Lord's service.",
    scripture_references: ["1 Samuel 1:19-20"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "What kind of bird brought Elijah food at the Kerith Ravine?",
    options: ["Ravens", "Doves", "Eagles", "Sparrows"],
    correct_option_index: 0,
    correct_answer: "Ravens",
    explanation: "The Lord commanded ravens to bring Elijah bread and meat morning and evening.",
    scripture_references: ["1 Kings 17:2-6"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "What relation was Jacob to Abraham?",
    options: ["Grandson", "Son", "Great-grandson", "Nephew"],
    correct_option_index: 0,
    correct_answer: "Grandson",
    explanation: "Jacob was the son of Isaac, who was Abraham's son.",
    scripture_references: ["Genesis 25:24-26"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "How many sons did Jacob have, forming the tribes of Israel?",
    options: ["Twelve", "Ten", "Thirteen", "Seven"],
    correct_option_index: 0,
    correct_answer: "Twelve",
    explanation: "Jacob's twelve sons became the ancestors of the twelve tribes of Israel.",
    scripture_references: ["Genesis 35:22-26"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Which tribe of Israel was set apart for temple and religious service?",
    options: ["Levi", "Judah", "Reuben", "Simeon"],
    correct_option_index: 0,
    correct_answer: "Levi",
    explanation: "The Levites were set apart to serve in the tabernacle and assist the priests.",
    scripture_references: ["Numbers 3:5-10"],
    category: "Exodus",
    difficulty: "medium",
  },
  {
    question: "What was the name of the southern kingdom after Israel split?",
    options: ["Judah", "Samaria", "Bethel", "Edom"],
    correct_option_index: 0,
    correct_answer: "Judah",
    explanation: "After Solomon's reign, the kingdom split into Israel in the north and Judah in the south.",
    scripture_references: ["1 Kings 12:16-20"],
    category: "Kings",
    difficulty: "medium",
  },
  {
    question: "To which empire did the southern kingdom of Judah eventually fall?",
    options: ["Babylon", "Assyria", "Persia", "Egypt"],
    correct_option_index: 0,
    correct_answer: "Babylon",
    explanation: "Nebuchadnezzar's Babylonian army destroyed Jerusalem and took Judah into exile.",
    scripture_references: ["2 Kings 25:1-21"],
    category: "Kings",
    difficulty: "medium",
  },
  {
    question: "In which prophet's book do we read about the valley of dry bones?",
    options: ["Ezekiel", "Isaiah", "Jeremiah", "Daniel"],
    correct_option_index: 0,
    correct_answer: "Ezekiel",
    explanation: "God showed Ezekiel a vision of dry bones coming to life as a picture of Israel's restoration.",
    scripture_references: ["Ezekiel 37:1-14"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "From which part of Adam's body did God form Eve?",
    options: ["A rib", "Dust of the ground", "Clay", "A bone from his foot"],
    correct_option_index: 0,
    correct_answer: "A rib",
    explanation: "The Lord caused Adam to sleep, took one of his ribs, and made it into a woman.",
    scripture_references: ["Genesis 2:21-22"],
    category: "Creation",
    difficulty: "easy",
  },
  {
    question: "What was the first bird Noah sent out from the ark?",
    options: ["A raven", "A dove", "An eagle", "A sparrow"],
    correct_option_index: 0,
    correct_answer: "A raven",
    explanation: "Noah first sent out a raven, which flew back and forth until the waters dried up.",
    scripture_references: ["Genesis 8:6-7"],
    category: "Creation",
    difficulty: "medium",
  },
  {
    question: "What was the name of Abraham's nephew who traveled with him?",
    options: ["Lot", "Ishmael", "Isaac", "Eliezer"],
    correct_option_index: 0,
    correct_answer: "Lot",
    explanation: "Lot journeyed with Abraham and later settled near Sodom.",
    scripture_references: ["Genesis 12:5"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Whom did God ask Abraham to sacrifice on Mount Moriah?",
    options: ["His son Isaac", "A ram", "His servant", "His nephew Lot"],
    correct_option_index: 0,
    correct_answer: "His son Isaac",
    explanation: "God tested Abraham by asking for Isaac, then provided a ram as a substitute.",
    scripture_references: ["Genesis 22:1-2"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "What did Rachel steal from her father Laban when she left with Jacob?",
    options: ["His household gods", "His flocks", "His tents", "His silver"],
    correct_option_index: 0,
    correct_answer: "His household gods",
    explanation: "Rachel secretly took her father's household idols as the family departed.",
    scripture_references: ["Genesis 31:19"],
    category: "Bible people",
    difficulty: "hard",
  },
  {
    question: "What was the name of Joseph's youngest brother?",
    options: ["Benjamin", "Reuben", "Judah", "Dan"],
    correct_option_index: 0,
    correct_answer: "Benjamin",
    explanation: "Benjamin was the youngest of Jacob's twelve sons, born to Rachel.",
    scripture_references: ["Genesis 35:24"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "Whose dream did Joseph correctly interpret while in prison, foretelling his own restoration?",
    options: ["The cupbearer's", "The baker's", "Pharaoh's", "The jailer's"],
    correct_option_index: 0,
    correct_answer: "The cupbearer's",
    explanation: "Joseph told the cupbearer he would be restored to Pharaoh's service in three days.",
    scripture_references: ["Genesis 40:9-13"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "In what was baby Moses hidden to save him from Pharaoh's decree?",
    options: ["A basket of bulrushes", "A cave", "A well", "His mother's tent"],
    correct_option_index: 0,
    correct_answer: "A basket of bulrushes",
    explanation: "Moses's mother placed him in a papyrus basket among the reeds of the Nile.",
    scripture_references: ["Exodus 2:3"],
    category: "Exodus",
    difficulty: "easy",
  },
  {
    question: "What was the first plague the Lord sent on Egypt?",
    options: ["Water turned to blood", "Frogs", "Locusts", "Darkness"],
    correct_option_index: 0,
    correct_answer: "Water turned to blood",
    explanation: "The Nile and all Egypt's water sources turned to blood, the first of ten plagues.",
    scripture_references: ["Exodus 7:20-21"],
    category: "Exodus",
    difficulty: "medium",
  },
  {
    question: "On what mountain did Moses receive the Law from God?",
    options: ["Mount Sinai", "Mount Nebo", "Mount Carmel", "Mount Ararat"],
    correct_option_index: 0,
    correct_answer: "Mount Sinai",
    explanation: "The Lord called Moses up Mount Sinai to receive the covenant law for Israel.",
    scripture_references: ["Exodus 19:20", "Exodus 24:12"],
    category: "Exodus",
    difficulty: "easy",
  },
  {
    question: "How did Rahab mark her house so the invading Israelites would spare it?",
    options: ["She tied a scarlet cord in the window", "She painted the door red", "She hung a white flag", "She lit a lamp in the doorway"],
    correct_option_index: 0,
    correct_answer: "She tied a scarlet cord in the window",
    explanation: "The spies instructed Rahab to tie a scarlet cord in her window as a sign for the invasion.",
    scripture_references: ["Joshua 2:18-21"],
    category: "Bible people",
    difficulty: "medium",
  },
  {
    question: "What did Gideon's men use to rout the Midianite army?",
    options: ["Trumpets, pitchers, and torches", "Swords and shields", "Chariots and horses", "Bows and arrows"],
    correct_option_index: 0,
    correct_answer: "Trumpets, pitchers, and torches",
    explanation: "Gideon's 300 men broke jars to reveal torches and blew trumpets, throwing the Midianites into panic.",
    scripture_references: ["Judges 7:16-22"],
    category: "Judges",
    difficulty: "medium",
  },
  {
    question: "Which judge of Israel was betrayed to the Philistines by Delilah?",
    options: ["Samson", "Gideon", "Ehud", "Jephthah"],
    correct_option_index: 0,
    correct_answer: "Samson",
    explanation: "Delilah discovered the secret of Samson's strength and betrayed him to the Philistines.",
    scripture_references: ["Judges 16:4-20"],
    category: "Judges",
    difficulty: "easy",
  },
  {
    question: "Whom did Samuel anoint as the first king of Israel?",
    options: ["Saul", "David", "Solomon", "Jonathan"],
    correct_option_index: 0,
    correct_answer: "Saul",
    explanation: "Samuel anointed Saul, son of Kish, to be Israel's first king.",
    scripture_references: ["1 Samuel 10:1"],
    category: "Kings",
    difficulty: "easy",
  },
  {
    question: "What did David use to defeat Goliath?",
    options: ["A sling and a stone", "A sword", "A spear", "His bare hands"],
    correct_option_index: 0,
    correct_answer: "A sling and a stone",
    explanation: "David struck Goliath in the forehead with a stone from his sling.",
    scripture_references: ["1 Samuel 17:49-50"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "How did David arrange for Uriah the Hittite to die?",
    options: ["He had him placed in the fiercest part of the battle", "He had him poisoned", "He exiled him", "He had him imprisoned"],
    correct_option_index: 0,
    correct_answer: "He had him placed in the fiercest part of the battle",
    explanation: "David instructed Joab to put Uriah where the fighting was hardest and then withdraw support.",
    scripture_references: ["2 Samuel 11:14-17"],
    category: "Kings",
    difficulty: "hard",
  },
  {
    question: "What was Cain's punishment for murdering Abel?",
    options: ["To be a restless wanderer on the earth", "Death", "Blindness", "Exile to Egypt"],
    correct_option_index: 0,
    correct_answer: "To be a restless wanderer on the earth",
    explanation: "The ground would no longer yield its strength to Cain, and he was cursed to wander.",
    scripture_references: ["Genesis 4:11-12"],
    category: "Creation",
    difficulty: "medium",
  },
  {
    question: "What was the secret of Samson's great strength?",
    options: ["His uncut hair", "His sandals", "His belt", "His shield"],
    correct_option_index: 0,
    correct_answer: "His uncut hair",
    explanation: "Samson's strength was tied to his Nazirite vow, symbolized by his uncut hair.",
    scripture_references: ["Judges 16:17"],
    category: "Judges",
    difficulty: "easy",
  },
  {
    question: "What did Joseph's brothers do to him out of jealousy?",
    options: ["Sold him into slavery", "Killed him", "Banished him", "Imprisoned him"],
    correct_option_index: 0,
    correct_answer: "Sold him into slavery",
    explanation: "Joseph's brothers sold him to Ishmaelite traders bound for Egypt.",
    scripture_references: ["Genesis 37:26-28"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Who succeeded Moses as leader of Israel?",
    options: ["Joshua", "Caleb", "Aaron", "Samuel"],
    correct_option_index: 0,
    correct_answer: "Joshua",
    explanation: "Joshua, Moses's assistant, led Israel into the Promised Land after Moses's death.",
    scripture_references: ["Deuteronomy 34:9", "Joshua 1:1-2"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "What was the name of David's father?",
    options: ["Jesse", "Saul", "Boaz", "Obed"],
    correct_option_index: 0,
    correct_answer: "Jesse",
    explanation: "David was the youngest son of Jesse of Bethlehem.",
    scripture_references: ["1 Samuel 16:1"],
    category: "Kings",
    difficulty: "medium",
  },
  {
    question: "How did the prophet Daniel end up living in Babylon?",
    options: ["He was taken captive in a Babylonian raid", "He moved there by choice", "He was born there", "He was sold as a slave by his brothers"],
    correct_option_index: 0,
    correct_answer: "He was taken captive in a Babylonian raid",
    explanation: "Daniel was among the young nobles of Judah taken captive to Babylon under Nebuchadnezzar.",
    scripture_references: ["Daniel 1:1-6"],
    category: "Prophets",
    difficulty: "medium",
  },
  {
    question: "What was the first thing God created?",
    options: ["Light", "Water", "Land", "Stars"],
    correct_option_index: 0,
    correct_answer: "Light",
    explanation: "God said, 'Let there be light,' on the first day of creation.",
    scripture_references: ["Genesis 1:3"],
    category: "Creation",
    difficulty: "easy",
  },
  {
    question: "On which day of creation did God make plants?",
    options: ["The third day", "The second day", "The fourth day", "The fifth day"],
    correct_option_index: 0,
    correct_answer: "The third day",
    explanation: "God gathered the waters and caused vegetation to spring up on the third day.",
    scripture_references: ["Genesis 1:11-13"],
    category: "Creation",
    difficulty: "easy",
  },
  {
    question: "How many of each kind of animal did Noah bring onto the ark?",
    options: ["Two", "One", "Seven", "Three"],
    correct_option_index: 0,
    correct_answer: "Two",
    explanation: "God instructed Noah to bring two of every kind of animal, male and female.",
    scripture_references: ["Genesis 6:19-20"],
    category: "Creation",
    difficulty: "easy",
  },
  {
    question: "What sign did God give as a symbol of His promise to Noah?",
    options: ["The rainbow", "A dove", "An olive branch", "A star"],
    correct_option_index: 0,
    correct_answer: "The rainbow",
    explanation: "God set the rainbow in the clouds as a sign He would never again flood the whole earth.",
    scripture_references: ["Genesis 9:12-13"],
    category: "Creation",
    difficulty: "easy",
  },
  {
    question: "What was the name of Moses's brother, who spoke to Pharaoh with him?",
    options: ["Aaron", "Joshua", "Caleb", "Nadab"],
    correct_option_index: 0,
    correct_answer: "Aaron",
    explanation: "Aaron served as Moses's spokesman before Pharaoh and later became Israel's first high priest.",
    scripture_references: ["Exodus 4:14-16"],
    category: "Exodus",
    difficulty: "easy",
  },
  {
    question: "Whose coat of many colors made his brothers jealous?",
    options: ["Joseph's", "Benjamin's", "Reuben's", "Judah's"],
    correct_option_index: 0,
    correct_answer: "Joseph's",
    explanation: "Jacob's favoritism, shown through the special coat, deepened his brothers' resentment of Joseph.",
    scripture_references: ["Genesis 37:3-4"],
    category: "Bible people",
    difficulty: "easy",
  },
  {
    question: "Who was thrown into a den of lions for praying to God three times a day?",
    options: ["Daniel", "Shadrach, Meshach, and Abednego", "Elijah", "Jeremiah"],
    correct_option_index: 0,
    correct_answer: "Daniel",
    explanation: "Daniel continued praying openly despite King Darius's decree and was thrown to the lions, unharmed.",
    scripture_references: ["Daniel 6:10-16"],
    category: "Prophets",
    difficulty: "easy",
  },
  {
    question: "Which prophet was swallowed by a great fish?",
    options: ["Jonah", "Daniel", "Elijah", "Noah"],
    correct_option_index: 0,
    correct_answer: "Jonah",
    explanation: "Jonah was swallowed by a great fish after fleeing from God's call to Nineveh.",
    scripture_references: ["Jonah 1:17"],
    category: "Prophets",
    difficulty: "easy",
  },
  {
    question: "Who betrayed Jesus with a kiss for thirty pieces of silver?",
    options: ["Judas Iscariot", "Peter", "Thomas", "John"],
    correct_option_index: 0,
    correct_answer: "Judas Iscariot",
    explanation: "Judas agreed to betray Jesus to the chief priests for thirty pieces of silver.",
    scripture_references: ["Matthew 26:14-16"],
    category: "Crucifixion",
    difficulty: "easy",
  },
  {
    question: "What gift-bearing visitors came to see the infant Jesus?",
    options: ["The wise men", "Shepherds", "Angels", "Roman soldiers"],
    correct_option_index: 0,
    correct_answer: "The wise men",
    explanation: "Wise men from the East brought gold, frankincense, and myrrh to honor the newborn king.",
    scripture_references: ["Matthew 2:1-11"],
    category: "Nativity",
    difficulty: "easy",
  },
  {
    question: "Which religious group repeatedly tried to trap Jesus with questions?",
    options: ["The Pharisees", "The Sadducees", "The Romans", "The Samaritans"],
    correct_option_index: 0,
    correct_answer: "The Pharisees",
    explanation: "The Pharisees often questioned Jesus, hoping to catch Him in His words.",
    scripture_references: ["Matthew 22:15"],
    category: "New Testament",
    difficulty: "medium",
  },
  {
    question: "What did Jesus do for His friend Lazarus?",
    options: ["Raised him from the dead", "Healed his blindness", "Forgave his sins", "Blessed his household"],
    correct_option_index: 0,
    correct_answer: "Raised him from the dead",
    explanation: "Jesus called Lazarus out of the tomb four days after his death.",
    scripture_references: ["John 11:38-44"],
    category: "Miracles",
    difficulty: "easy",
  },
  {
    question: "What was Joseph's, Jesus's earthly father, occupation?",
    options: ["Carpenter", "Fisherman", "Shepherd", "Tax collector"],
    correct_option_index: 0,
    correct_answer: "Carpenter",
    explanation: "The people of Nazareth knew Jesus as the carpenter's son.",
    scripture_references: ["Matthew 13:55"],
    category: "Nativity",
    difficulty: "easy",
  },
  {
    question: "Who wanted baby Jesus killed and ordered the massacre of Bethlehem's infants?",
    options: ["Herod the Great", "Pontius Pilate", "Caesar Augustus", "Caiaphas"],
    correct_option_index: 0,
    correct_answer: "Herod the Great",
    explanation: "Herod, threatened by news of a newborn king, ordered the killing of young boys in Bethlehem.",
    scripture_references: ["Matthew 2:13-16"],
    category: "Nativity",
    difficulty: "medium",
  },
  {
    question: "What did the Holy Spirit look like when the disciples received it at Pentecost?",
    options: ["Tongues of fire", "A dove", "A bright cloud", "A strong wind alone"],
    correct_option_index: 0,
    correct_answer: "Tongues of fire",
    explanation: "Divided tongues like fire rested on each of the disciples at Pentecost.",
    scripture_references: ["Acts 2:3-4"],
    category: "New Testament",
    difficulty: "medium",
  },
  {
    question: "How did Paul escape the city of Damascus when his life was threatened?",
    options: ["In a basket lowered through the city wall", "Through the main gate at night", "Disguised as a merchant", "By boat"],
    correct_option_index: 0,
    correct_answer: "In a basket lowered through the city wall",
    explanation: "The disciples helped Paul escape by lowering him in a basket through an opening in the wall.",
    scripture_references: ["Acts 9:23-25"],
    category: "Paul's journeys",
    difficulty: "medium",
  },
];
