enum AppFeature {
  appShell,

  communityRead,
  communityPost,
  communityInteract,
  socialProfile,
  socialFollowing,
  publicChurchDirectory,
  publicEvents,
  eventRsvp,
  bibleReading,
  dailyWord,
  notifications,
  savedItems,
  graceCircles,
  graceRooms,

  directMessages,
  socialConnectionRequests,

  churchHome,
  churchTransfer,
  churchPublicPage,
  churchTestimonies,

  memberDirectory,
  attendance,
  announcements,
  ministryManagement,
  studyGroups,
  privatePrayerCare,
  counseling,
  scheduling,
  roleManagement,
  churchFinance,
  churchAnalytics,
  liveManagement,
}

extension AppFeatureLabel on AppFeature {
  String get label {
    return switch (this) {
      AppFeature.appShell => 'Grace Connect',
      AppFeature.communityRead => 'Community',
      AppFeature.communityPost => 'Community posting',
      AppFeature.communityInteract => 'Community interaction',
      AppFeature.socialProfile => 'Public profile',
      AppFeature.socialFollowing => 'Following',
      AppFeature.publicChurchDirectory => 'Church directory',
      AppFeature.publicEvents => 'Public events',
      AppFeature.eventRsvp => 'Event RSVP',
      AppFeature.bibleReading => 'Bible',
      AppFeature.dailyWord => 'Daily Word',
      AppFeature.notifications => 'Notifications',
      AppFeature.savedItems => 'Saved',
      AppFeature.graceCircles => 'Grace Circles',
      AppFeature.graceRooms => 'Grace Rooms',
      AppFeature.directMessages => 'Inbox',
      AppFeature.socialConnectionRequests => 'Connection requests',
      AppFeature.churchHome => 'Church home',
      AppFeature.churchTransfer => 'Church transfer',
      AppFeature.churchPublicPage => 'Church public page',
      AppFeature.churchTestimonies => 'Testimonies',
      AppFeature.memberDirectory => 'Member directory',
      AppFeature.attendance => 'Attendance',
      AppFeature.announcements => 'Announcements',
      AppFeature.ministryManagement => 'Ministry management',
      AppFeature.studyGroups => 'Study groups',
      AppFeature.privatePrayerCare => 'Private prayer care',
      AppFeature.counseling => 'Counseling',
      AppFeature.scheduling => 'Scheduling',
      AppFeature.roleManagement => 'Role management',
      AppFeature.churchFinance => 'Finance',
      AppFeature.churchAnalytics => 'Analytics',
      AppFeature.liveManagement => 'Live management',
    };
  }
}
