android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4096m
org.gradle.daemon=false
org.gradle.vfs.watch=false
org.gradle.caching=false
android.agp.useNewApkCreator=false
org.gradle.warning.mode=summary
org.gradle.parallel=false
org.gradle.workers.max=1
android.enableAapt2Daemon=false
android.aapt2FromMavenOverride=/Users/Bakers/Library/Android/sdk/build-tools/36.0.0/aapt2
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home
kotlin.compiler.execution.strategy=in-process
