android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4096m
org.gradle.daemon=false
org.gradle.vfs.watch=false
org.gradle.caching=false
android.agp.useNewApkCreator=false
org.gradle.warning.mode=summary
org.gradle.parallel=false
org.gradle.workers.max=1
android.enableAapt2Daemon=false
kotlin.compiler.execution.strategy=in-process
