// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpvkxqm00jroFB19ifSh9slEJ4DBQOfZE',
    appId: '1:47100126669:web:59899cd353f6bc85a65084',
    messagingSenderId: '47100126669',
    projectId: 'graceconnect-9a97c',
    authDomain: 'graceconnect-9a97c.firebaseapp.com',
    storageBucket: 'graceconnect-9a97c.firebasestorage.app',
    measurementId: 'G-EF92D44WSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbE9rFDj8htVoaj-XruVHdQNnwqTDvEm0',
    appId: '1:47100126669:android:c639ef7425b29bc6a65084',
    messagingSenderId: '47100126669',
    projectId: 'graceconnect-9a97c',
    storageBucket: 'graceconnect-9a97c.firebasestorage.app',
    measurementId: 'G-EF92D44WSB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpvkxqm00jroFB19ifSh9slEJ4DBQOfZE',
    appId: '1:47100126669:ios:dbd497750ab61d6ea65084',
    messagingSenderId: '47100126669',
    projectId: 'graceconnect-9a97c',
    storageBucket: 'graceconnect-9a97c.firebasestorage.app',
    measurementId: 'G-EF92D44WSB',
    iosBundleId: 'com.example.graceconnect',
  );
}
